# Generated by Django 4.0.1 on 2022-01-05 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Movie Title', max_length=100)),
                ('comment', models.TextField(null=True)),
                ('synopsis', models.TextField(null=True)),
                ('rating', models.FloatField(default=0)),
                ('your_rating', models.FloatField(default=0)),
                ('reviewed', models.BooleanField(default=False)),
                ('release_date', models.DateField(verbose_name='release date')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Actor Name', max_length=100)),
                ('movie', models.ForeignKey(default='Movie', on_delete=django.db.models.deletion.CASCADE, to='movie.movie')),
            ],
        ),
    ]
